cc_test(
    name = "bullets.test",
    size = "small",
    srcs = ["bullets.test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//parser:state",
        "//parser/lexers:bullets"
    ]
)
