cc_test(
    name = "itemize.test",
    size = "small",
    srcs = ["itemize.test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//parser:state",
        "//parser/lexers:itemize"
    ]
)
