cc_library(
    name = "itemize",
    srcs = ["itemize.cpp"],
    hdrs = ["itemize.hpp"],
    deps = [
        "//parser:state",
        "//parser:lexer"
    ],
    visibility = ["//parser:__subpackages__"]
)

cc_library(
    name = "enumerate",
    srcs = ["enumerate.cpp"],
    hdrs = ["enumerate.hpp"],
    deps = [
        "//parser:state",
        "//parser:lexer"
    ],
    visibility = ["//parser:__subpackages__"]
)
