cc_library(
    name = "bullets",
    srcs = ["bullets.cpp"],
    hdrs = ["bullets.hpp"],
    deps = [
        "//parser:state",
        "//parser:lexer"
    ],
    visibility = ["//parser:__subpackages__"],
)
