cc_library(
    name = "itemize",
    srcs = ["itemize.cpp"],
    hdrs = ["itemize.hpp"],
    deps = [
        "//parser:state",
        "//parser:lexer"
    ],
    visibility = ["//parser:__subpackages__"],
)
