cc_test(
    name = "parser.test",
    size = "small",
    srcs = ["parser.test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//parser"
    ]
)

cc_test(
    name = "state.test",
    size = "small",
    srcs = ["state.test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//parser:state"
    ]
)
