cc_test(
    name = "parser.tests.arrow",
    size = "small",
    srcs = ["arrow.test.cpp"],
    deps = [
        "//parser",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "parser.tests.enumerate",
    size = "small",
    srcs = ["enumerate.test.cpp"],
    deps = [
        "//parser",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "parser.tests.footer",
    size = "small",
    srcs = ["footer.test.cpp"],
    deps = [
        "//parser",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "parser.tests.header",
    size = "small",
    srcs = ["header.test.cpp"],
    deps = [
        "//parser",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "parser.tests.headline",
    size = "small",
    srcs = ["headline.test.cpp"],
    deps = [
        "//parser",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "parser.tests.itemize",
    size = "small",
    srcs = ["itemize.test.cpp"],
    deps = [
        "//parser",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "parser.tests.math.block",
    size = "small",
    srcs = ["math.block.test.cpp"],
    deps = [
        "//parser",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "parser.tests.math.inline",
    size = "small",
    srcs = ["math.inline.test.cpp"],
    deps = [
        "//parser",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "parser.tests.misc",
    size = "small",
    srcs = ["misc.test.cpp"],
    deps = [
        "//parser",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "parser.tests.verb.block",
    size = "small",
    srcs = ["verb.block.test.cpp"],
    deps = [
        "//parser",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "parser.tests.verb.inline",
    size = "small",
    srcs = ["verb.inline.test.cpp"],
    deps = [
        "//parser",
        "@googletest//:gtest_main",
    ],
)
