load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "googletest",
    strip_prefix = "googletest-release-1.11.0",
    urls = ["https://github.com/google/googletest/archive/refs/tags/release-1.11.0.zip"],
)

http_archive(
    name = "cpp_utilities",
    build_file = "@//:BUILD.cpp_utilities",
    sha256 = "1654e899a2a4675dd866f924d39e4984ac2d212093fc492bfa6e57dab97c4f59",
    strip_prefix = "cpp-utilities-0.1.0-alpha.1",
    urls = ["https://github.com/caydenlund/cpp-utilities/archive/refs/tags/v0.1.0-alpha.1.zip"],
)
